#include "key_map.h"

#include "key_scan.h"

#include <avr/pgmspace.h>
#include <LUFA/Drivers/USB/USB.h>


static const uint8_t KEY_MAPPING[NUM_COLUMNS][NUM_ROWS] PROGMEM = {
    {HID_KEYBOARD_SC_BACKSPACE, HID_KEYBOARD_SC_P, HID_KEYBOARD_SC_O, HID_KEYBOARD_SC_I,
     HID_KEYBOARD_SC_U, HID_KEYBOARD_SC_Y, HID_KEYBOARD_SC_T, HID_KEYBOARD_SC_R,
     HID_KEYBOARD_SC_E, HID_KEYBOARD_SC_W, HID_KEYBOARD_SC_Q, HID_KEYBOARD_SC_ESCAPE    
    },

    {HID_KEYBOARD_SC_ENTER, HID_KEYBOARD_SC_SEMICOLON_AND_COLON, HID_KEYBOARD_SC_L, HID_KEYBOARD_SC_K,
     HID_KEYBOARD_SC_J, HID_KEYBOARD_SC_H, HID_KEYBOARD_SC_G, HID_KEYBOARD_SC_F,    
     HID_KEYBOARD_SC_D, HID_KEYBOARD_SC_S, HID_KEYBOARD_SC_A, HID_KEYBOARD_SC_TAB    
    },

    {HID_KEYBOARD_SC_RIGHT_SHIFT, HID_KEYBOARD_SC_UP_ARROW, HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN, HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN,
     HID_KEYBOARD_SC_M, HID_KEYBOARD_SC_N, HID_KEYBOARD_SC_B, HID_KEYBOARD_SC_V,
     HID_KEYBOARD_SC_C, HID_KEYBOARD_SC_X, HID_KEYBOARD_SC_Z, HID_KEYBOARD_SC_LEFT_SHIFT 
    },

    {HID_KEYBOARD_SC_RIGHT_ARROW, HID_KEYBOARD_SC_DOWN_ARROW, HID_KEYBOARD_SC_LEFT_ARROW, HID_KEYBOARD_SC_RIGHT_CONTROL,
     0, HID_KEYBOARD_SC_SPACE, HID_KEYBOARD_SC_SPACE, 0,
     HID_KEYBOARD_SC_LEFT_ALT, HID_KEYBOARD_SC_LEFT_GUI, HID_KEYBOARD_SC_LEFT_CONTROL, HID_KEYBOARD_SC_LEFT_CONTROL 
    }
};

uint8_t get_scancode(uint8_t col, uint8_t row) {
    return pgm_read_byte(&KEY_MAPPING[col][row]);
}

